// vp-tap is the BPF-based traffic capture daemon for the validation platform.
//
// Pipeline (CONTEXT.md D-01 / D-03 / RESEARCH §6):
//
//   BPF tracepoints  →  ringbuf  →  reassembler (Plan 01-04)
//                                    └─ transformer (Plan 01-05: redact + sample + filter)
//                                          └─ batcher  →  collectorclient (Plan 01-05)
//
// Plus two sibling goroutines coordinated by atomic.Pointer[DynamicConfig]:
//
//   serviceDiscoveryLoop (Plan 01-06)   — K8s Service informer → POST /api/services
//   configPollLoop       (Plan 01-05)   — GET /api/agent/config → swap DynamicConfig
//
// Plan 01-02 lands the *shell* of this pipeline: config loaders, structured
// logging, /metrics + /ready + /healthz HTTP endpoints, and the goroutine
// scaffolding with TODO placeholders for the loops that other plans fill in.
//
// Stop with SIGINT or SIGTERM.

package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"

	"vp-tap/internal/config"
	bpf "vp-tap/internal/ebpf"
	"vp-tap/internal/k8s/podinformer"
	"vp-tap/internal/logging"
	"vp-tap/internal/metrics"
)

const (
	heartbeatInterval = 30 * time.Second

	// cgroup v2 root inside the container. The DaemonSet must hostPath-mount
	// /sys/fs/cgroup from the host so the informer can stat() pod-cgroup
	// slice directories to learn cgroup IDs.
	cgroupRoot = "/sys/fs/cgroup"

	// Default ConfigMap mount path (D-02). Overridden via BEHAVIORAL_CONFIG_PATH env.
	defaultBehavioralPath = "/etc/vp-tap/config.yaml"
)

// Event kinds emitted by probe.bpf.c.
const (
	kindWrite uint8 = 1
	kindRead  uint8 = 2
	kindClose uint8 = 3
)

func main() {
	logging.Setup(logging.MustLevel(os.Getenv("LOG_LEVEL")))
	slog.Info("vp-tap starting", "pid", os.Getpid())

	mustRaiseMemlock()

	staticCfg, err := config.LoadStatic()
	if err != nil {
		slog.Error("static config load failed", "err", err)
		os.Exit(1)
	}
	behavioralPath := os.Getenv("BEHAVIORAL_CONFIG_PATH")
	if behavioralPath == "" {
		behavioralPath = defaultBehavioralPath
	}
	behavioral, err := config.LoadBehavioral(behavioralPath)
	if err != nil {
		slog.Error("behavioral config load failed", "path", behavioralPath, "err", err)
		os.Exit(1)
	}
	slog.Info("config loaded",
		"node", staticCfg.NodeName,
		"platform_url", staticCfg.PlatformURL,
		"collector_url", staticCfg.CollectorURL,
		"max_body_bytes", behavioral.MaxBodyBytes,
		"reassembly_idle_ttl", behavioral.ReassemblyIdleTTL,
		"metrics_port", behavioral.MetricsPort,
	)

	// DynamicConfig is shared across goroutines via atomic.Pointer.
	// configPollLoop (Plan 01-05) overwrites; transformer/reassembler/
	// collectorclient read by Load() each time they need a snapshot.
	dyncfg := &atomic.Pointer[config.DynamicConfig]{}
	dyncfg.Store(config.DefaultDynamicConfig())

	ctx, cancel := installSignalHandler()
	defer cancel()

	objs := mustLoadBPFObjects()
	defer objs.Close()

	links := mustAttachAllTracepoints(objs)
	for _, l := range links {
		defer l.Close()
	}

	rd := mustOpenRingbuf(objs)
	defer rd.Close()

	index := mustBuildPodIndex(staticCfg.NodeName)
	var captured uint64

	// Goroutine fleet. Each exits on ctx cancellation; shutdown handler
	// propagates by closing the ringbuf so the capture loop unblocks.
	var wg sync.WaitGroup
	wg.Add(7)
	go runShutdownHandler(ctx, &wg, rd)
	go runHeartbeat(ctx, &wg, &captured, index)
	go runPodInformer(ctx, &wg, index)
	go runCaptureLoop(ctx, &wg, rd, index, &captured)
	go runMetricsServer(ctx, &wg, behavioral.MetricsPort, index)
	go runServiceDiscoveryLoop(ctx, &wg, staticCfg, dyncfg)
	go runConfigPollLoop(ctx, &wg, staticCfg, dyncfg)

	wg.Wait()
	slog.Info("vp-tap shutdown complete")
}

// mustRaiseMemlock removes the RLIMIT_MEMLOCK cap so BPF maps can be
// allocated. On kernels < 5.11 the default 64 KiB ceiling rejects our
// 32 MiB ringbuf; on newer kernels the call is a harmless no-op.
func mustRaiseMemlock() {
	if err := rlimit.RemoveMemlock(); err != nil {
		slog.Error("removing memlock", "err", err)
		os.Exit(1)
	}
}

// mustLoadBPFObjects parses the bpf2go-generated ELF blob, makes the
// bpf(BPF_PROG_LOAD) and bpf(BPF_MAP_CREATE) syscalls, returns kernel fds.
func mustLoadBPFObjects() bpf.ProbeObjects {
	objs := bpf.ProbeObjects{}
	if err := bpf.LoadProbeObjects(&objs, nil); err != nil {
		slog.Error("loading bpf objects", "err", err)
		os.Exit(1)
	}
	return objs
}

// mustAttachAllTracepoints wires every BPF program to its syscall
// tracepoint. Each program is generated by bpf2go from a SEC() directive
// in probe.bpf.c. Returns the link slice so callers can defer Close().
func mustAttachAllTracepoints(objs bpf.ProbeObjects) []link.Link {
	attaches := []struct {
		group string
		name  string
		prog  *ebpf.Program
	}{
		{"syscalls", "sys_enter_write", objs.TraceSysEnterWrite},
		{"syscalls", "sys_enter_read", objs.TraceSysEnterRead},
		{"syscalls", "sys_exit_read", objs.TraceSysExitRead},
		{"syscalls", "sys_enter_close", objs.TraceSysEnterClose},
	}
	links := make([]link.Link, 0, len(attaches))
	for _, a := range attaches {
		l, err := link.Tracepoint(a.group, a.name, a.prog, nil)
		if err != nil {
			slog.Error("attaching tracepoint", "group", a.group, "name", a.name, "err", err)
			os.Exit(1)
		}
		slog.Info("attached tracepoint", "group", a.group, "name", a.name)
		links = append(links, l)
	}
	return links
}

// mustOpenRingbuf opens the userspace end of the BPF ringbuf map.
func mustOpenRingbuf(objs bpf.ProbeObjects) *ringbuf.Reader {
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		slog.Error("opening ringbuf reader", "err", err)
		os.Exit(1)
	}
	return rd
}

// installSignalHandler returns a context cancelled on SIGINT/SIGTERM.
func installSignalHandler() (context.Context, context.CancelFunc) {
	return signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
}

// mustBuildPodIndex constructs the cgroup_id → *v1.Pod index against the
// in-cluster K8s API. Returns the index without starting it — runPodInformer
// does that in its own goroutine.
func mustBuildPodIndex(nodeName string) *podinformer.Index {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		slog.Error("loading in-cluster K8s config", "err", err)
		os.Exit(1)
	}
	client, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		slog.Error("constructing K8s client", "err", err)
		os.Exit(1)
	}
	resolver := podinformer.NewFSCgroupResolver(cgroupRoot)
	return podinformer.NewIndex(client, nodeName, resolver)
}

// runShutdownHandler waits for SIGTERM/SIGINT and closes the ringbuf so
// the capture loop unblocks with ringbuf.ErrClosed.
func runShutdownHandler(ctx context.Context, wg *sync.WaitGroup, rd *ringbuf.Reader) {
	defer wg.Done()
	<-ctx.Done()
	slog.Info("shutdown signal received, closing ringbuf")
	_ = rd.Close()
}

// runHeartbeat logs a "still alive" line with capture count + index size
// every heartbeatInterval. Useful when traffic is sparse.
func runHeartbeat(ctx context.Context, wg *sync.WaitGroup, captured *uint64, idx *podinformer.Index) {
	defer wg.Done()
	ticker := time.NewTicker(heartbeatInterval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			slog.Info("heartbeat",
				"captured", atomic.LoadUint64(captured),
				"indexed_cgroups", idx.Size())
		}
	}
}

// runPodInformer runs the K8s informer goroutine. Blocks until ctx done.
func runPodInformer(ctx context.Context, wg *sync.WaitGroup, idx *podinformer.Index) {
	defer wg.Done()
	idx.Run(ctx)
}

// runCaptureLoop drains the ringbuf and switches on event kind.
// Plan 01-04 replaces the in-loop logging with a real reassembler.
func runCaptureLoop(ctx context.Context, wg *sync.WaitGroup, rd *ringbuf.Reader, idx *podinformer.Index, captured *uint64) {
	defer wg.Done()
	slog.Info("events ringbuf open; waiting for HTTP traffic on this node")
	_ = ctx // Plan 01-04 uses ctx for backpressure on the pairs channel.

	var e bpf.ProbeEvent
	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				slog.Info("events ringbuf closed", "total_captured", atomic.LoadUint64(captured))
				return
			}
			slog.Warn("events ringbuf read error", "err", err)
			metrics.RingbufDropsTotal.WithLabelValues("decode_error").Inc()
			continue
		}

		if err := binary.Read(bytes.NewReader(record.RawSample), binary.LittleEndian, &e); err != nil {
			slog.Warn("events decode error", "err", err)
			metrics.RingbufDropsTotal.WithLabelValues("decode_error").Inc()
			continue
		}

		switch e.Kind {
		case kindWrite, kindRead:
			n := int(e.Len)
			if n > len(e.Data) {
				n = len(e.Data)
			}
			line := firstHTTPLine(e.Data[:n])
			if line == "" {
				continue
			}
			atomic.AddUint64(captured, 1)
			podLabel := "?"
			if p, ok := idx.Lookup(e.CgroupId); ok {
				podLabel = p.Namespace + "/" + p.Name
			} else {
				metrics.AttributionUnknownTotal.WithLabelValues("pre_sync").Inc()
			}
			kindLabel := "write"
			if e.Kind == kindRead {
				kindLabel = "read"
			}
			slog.Debug("captured event",
				"kind", kindLabel,
				"cgroup", e.CgroupId,
				"pid", e.Pid,
				"fd", e.Fd,
				"pod", podLabel,
				"line", line)
		case kindClose:
			// Plan 01-04 wires this into reassembly buffer eviction.
			_ = e
		default:
			slog.Warn("events unknown kind", "kind", e.Kind)
		}
	}
}

// runMetricsServer serves /metrics, /ready, /healthz on the configured
// port. /ready blocks success on the pod informer's initial sync (so the
// Helm chart's readinessProbe gates traffic until the informer is fresh).
// /healthz is always 200 — used by the livenessProbe.
func runMetricsServer(ctx context.Context, wg *sync.WaitGroup, port int, idx *podinformer.Index) {
	defer wg.Done()

	mux := http.NewServeMux()
	mux.Handle("/metrics", metrics.Handler())
	mux.HandleFunc("/ready", func(w http.ResponseWriter, _ *http.Request) {
		if idx.HasSynced() {
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("ready"))
			return
		}
		w.WriteHeader(http.StatusServiceUnavailable)
		_, _ = w.Write([]byte("informer not synced"))
	})
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})

	srv := &http.Server{
		Addr:              fmt.Sprintf(":%d", port),
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
	}

	// ListenAndServe blocks; ctx-cancel triggers Shutdown via goroutine.
	go func() {
		<-ctx.Done()
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(shutdownCtx)
	}()

	slog.Info("metrics server listening", "addr", srv.Addr)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		slog.Error("metrics server error", "err", err)
	}
}

// runServiceDiscoveryLoop is the Plan 01-02 placeholder. Plan 01-06 wires
// the actual K8s Service informer + PlatformClient.RegisterService loop.
func runServiceDiscoveryLoop(ctx context.Context, wg *sync.WaitGroup, _ *config.StaticConfig, _ *atomic.Pointer[config.DynamicConfig]) {
	defer wg.Done()
	slog.Info("serviceDiscoveryLoop placeholder — Plan 01-06 wires the real loop")
	<-ctx.Done()
}

// runConfigPollLoop is the Plan 01-02 placeholder. Plan 01-05 wires the
// actual ConfigClient.Fetch + atomic.Pointer swap.
func runConfigPollLoop(ctx context.Context, wg *sync.WaitGroup, _ *config.StaticConfig, _ *atomic.Pointer[config.DynamicConfig]) {
	defer wg.Done()
	slog.Info("configPollLoop placeholder — Plan 01-05 wires the real loop")
	<-ctx.Done()
}

// httpLinePrefixes is the set of accepted leading tokens for an HTTP/1.1
// request line or status line. Kept for the diagnostic log path until
// Plan 01-04's reassembler takes over.
var httpLinePrefixes = []string{
	"HTTP/", // response status line
	"GET ", "POST ", "PUT ", "DELETE ",
	"HEAD ", "PATCH ", "OPTIONS ", "CONNECT ", "TRACE ",
}

// firstHTTPLine extracts the request line or status line from a buffer
// that the in-kernel filter already pre-screened as HTTP-shaped.
func firstHTTPLine(b []byte) string {
	idx := bytes.IndexAny(b, "\r\n")
	if idx < 0 {
		idx = len(b)
	}
	s := string(b[:idx])
	for _, p := range httpLinePrefixes {
		if strings.HasPrefix(s, p) {
			return s
		}
	}
	return ""
}
